version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - dbnet

  server:
    container_name: server
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - dbnet
    links:
      - "postgres:db"
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./server/node_modules
      - ./server:/app

  client:
    container_name: client
    build:
      context: ./client
    ports:
      - '5173:5173'
    volumes:
      - ./client/node_modules
      - ./client:/app
    restart: always
    depends_on:
      - server

networks:
  dbnet:
    driver: bridge

volumes:
  pgdata:

# TODO fix postgres connection like here
# https://github.com/alexdevero/docker-nestjs-react-postgres/tree/master