version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8.2-rc1-alpine
    container_name: wimm-apis-redis
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - '${REDIS_PORT}:6379'
    command: redis-server --bind localhost --bind 0.0.0.0 --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data/cache

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    links:
      - "postgres:db"
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server/node_modules
      - ./server:/app

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./client/node_modules
      - ./client:/app
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
      - server

volumes:
  pgdata:
  cache:
    driver: local
